# Thanks @ssp97 for the initial work on this file.
name: Build ChatDACS One-Click-To-Deploy Package (ChatDACS一键运行包构建)
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version:
          - 14
        architecture:
          - x64
    name: Build On：${{ matrix.os }}_${{ matrix.architecture }} - Node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: "npm"
          cache-dependency-path: |
            ./packages-lock.json
            plugins/package-lock.json

      - name: Remove Other Platforms go-cqhttp
        run: rm ./plugins/go-cqhttp/go-cqhttp

      - name: Clean Install Modules
        run: |
          npm ci --production
          cd ./plugins/
          npm ci --production
          rm package.json
          rm package-lock.json
          cd ..

      - name: Install pkg Tool
        run: npm i pkg -g

      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#detecting-the-operating-system
      - name: Use pkg to Package on Windows
        if: runner.os == 'Windows'
        run: pkg -t node${{ matrix.node_version }}-windows . --compress GZip

      - name: Use pkg to Package on Linux
        if: runner.os == 'Linux'
        run: pkg -t node${{ matrix.node_version }}-linux . --compress GZip

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Declare VERSION
        run: |
          node -e "
            const fs = require('fs');
            const version = require('./version.json');
            fs.writeFileSync('version-number', 'VERSION_NUMBER=' + version.versionNumber);
          "
          cat ./version-number >> $GITHUB_ENV
          echo ${{ env }}

      - name: Pre-compress
        run: |
          npm i archiver
          node -e "
            const archiver = require('archiver');
            const fs = require('fs');
            const path = require('path');
            const output = fs.createWriteStream(path.join(__dirname, 'ChatDACS-${{ env.VERSION_NUMBER }}_${{ runner.os }}.zip'));
            const archive = archiver('zip', {
              zlib: { level: 9 } // Sets the compression level. 9 is the max compression.
            });
            archive.pipe(output);
            archive.directory('./config/', 'config');
            archive.directory('./static/', 'static');
            archive.directory('./plugins/', 'plugins');
            archive.file('./README.md', { name: 'README.md' });
            archive.file('./LICENSE', { name: 'LICENSE' });
            archive.file('./chatdacs.exe', { name: 'chatdacs.exe' });
            archive.file('./chatdacs', { name: 'chatdacs' });
            archive.finalize();
          "

      - name: Get Current Time
        id: time
        run: echo "::set-output name=today::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ChatDACS-${{ env.VERSION_NUMBER }}_${{ runner.os }}-${{ steps.time.outputs.today }}
          path: ChatDACS-${{ env.VERSION_NUMBER }}_${{ runner.os }}.zip
          if-no-files-found: error
