# Thanks @ssp97 for the initial work on this file.
name: Build ChatDACS One-Click-To-Deploy Package (ChatDACS一键运行包构建)
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

# https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
jobs:
  build:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        os: [linux-x64, linux-arm64, windows-x64, windows-x86, windows-arm64, macos-x64, macos-arm64]
        include:
          - os: linux-x64
            runs-on: ubuntu-24.04
          - os: linux-arm64
            runs-on: ubuntu-24.04-arm
          - os: windows-x64
            runs-on: windows-2022-x64
          - os: windows-x86
            runs-on: windows-2022-win32
          - os: windows-arm64
            runs-on: windows-2022-arm64
          - os: macos-x64
            # macos-13 was the last x86_64 runner
            runs-on: macos-13
          - os: macos-arm64
            # macos-14+ (including latest) are ARM64 runners
            runs-on: macos-latest
        node_version:
          - 18
    name: Build On：${{ matrix.os }} - Node ${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'npm'
          cache-dependency-path: |
            ./package-lock.json

      - name: Remove go-cqhttp On Windows
        if: runner.os == 'Windows'
        run: rm ./plugins/go-cqhttp/go-cqhttp

      - name: Remove go-cqhttp.exe On Linux
        if: runner.os == 'Linux'
        run: |
          rm ./plugins/go-cqhttp/go-cqhttp_windows_amd64.exe
          rm ./plugins/go-cqhttp/go-cqhttp.bat

      - name: Clean Install Modules
        run: |
          npm ci --production

      - name: Install pkg Tool
        run: npm i pkg -g

      - name: Install sequelize-cli
        run: npm i sequelize-cli

      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#detecting-the-operating-system
      - name: Use pkg To Package
        run: pkg -t node${{ matrix.node_version }}-${{ matrix.os }} . --compress Brotli

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Declare VERSION
        shell: bash
        run: |
          VERSION_NUMBER=$(jq -r '.version' package.json)
          echo "VERSION_NUMBER=v$VERSION_NUMBER" >> $GITHUB_ENV

      - name: Pre-compress
        shell: bash
        run: |
          npm i archiver
          node -e "
            const archiver = require('archiver');
            const fs = require('fs');
            const path = require('path');
            const output = fs.createWriteStream(path.join(__dirname, 'ChatDACS-${{ env.VERSION_NUMBER }}_${{ matrix.os }}.zip'));
            const archive = archiver('zip', {
              zlib: { level: 9 }
            });
            archive.pipe(output);
            archive.directory('./config/', 'config');
            archive.directory('./static/', 'static');
            archive.directory('./plugins/', 'plugins');
            archive.directory('./migrations/', 'migrations');
            archive.directory('./node_modules', 'node_modules');
            archive.file('./README.md', { name: 'README.md' });
            archive.file('./LICENSE', { name: 'LICENSE' });
            archive.file('./package.json', { name: 'package.json' });
            archive.file('./chatdacs.exe', { name: 'chatdacs.exe' });
            archive.file('./chatdacs', { name: 'chatdacs' });
            archive.finalize();
          "

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChatDACS-${{ env.VERSION_NUMBER }}_${{ matrix.os }}_$(date -u +'%Y%m%d%H%M%S')
          path: ChatDACS-${{ env.VERSION_NUMBER }}_${{ matrix.os }}.zip
          if-no-files-found: error
